### ISSUE TITLE
No option to run tslint using tsconfig file without any modifications

### ISSUE THREAD

**Issue by mnasyrov** [wjohnsto/tsconfig-lint#2]
There is no option to run `tslint` in a readonly mode. I need to run it against files declared by `filesGlob` field of `tsconfig.json` file only without any modifications in the file.

Please implement a similar mode to `--use-glob` CLI option which does not rewrite `tsconfig.json`.

**Comment by wjohnsto** [comment]
Are you referring to not modifying the `tsconfig.json`, not modifying the `files` array (yet still using `filesGlob`), or not modifying the individual files when performing the lint?

**Comment by mnasyrov** [comment]
Yes, it's about to do not modify 'tsconfig.json'.

**Comment by wjohnsto** [comment]
If you are using the CLI, simply omitting the `--use-glob` parameter should fix this. If you are not using the CLI, then something like the following will work:

``` typescript
import * as lint from 'tsconfig-lint';
lint({
    configPath: '.',
    cwd: process.cwd(),
    useGlob: false
}, (err) => {
    //...
});
```

Note `useGlob: false` is the default behavior, but it should prevent any modifications to `tsconfig.json`

**Comment by mnasyrov** [comment]
Running `tsconfig-lint` without CLI parameters recursively checks all typescript files under a current directory while I need to skip some child directories. A valid file set is already declared by `filesGlob` of `tsconfig.json` so it may be convenient to use `--use-glob` parameter in couple with another parameter which disables updating `tsconfig.json`.

**Comment by wjohnsto** [comment]
Ok, so you want to be able to specify `filesGlob`, but when you run tsconfig-lint you want it to use `filesGlob` without modifying the `files` array?

**Comment by mnasyrov** [comment]
Yes, it's right.

**Comment by wjohnsto** [comment]
In `v0.9.0` you can use `--use-glob` without effecting the `tsconfig.json`. When you specify `--use-glob` the `filesGlob` array will be used in place of `files`.
