### ISSUE TITLE
How to specify the configuration file to use

### ISSUE THREAD

**Issue by dsebastien** [wjohnsto/tsconfig-lint#4]
Currently I've created a tslint.json file (https://github.com/dsebastien/angularjs-webpack-starter/blob/master/tslint.json) containing my configuration. Can I pass the path to the config file to use to tsconfig-lint and have it pass it as "-c, --config" to tslint?

**Comment by wjohnsto** [comment]
tsconfig-lint is currently not setup to work with a `tslint.json`, instead you put your rules in the `tsconfig.json`. You can see an example [here](/wjohnsto/tsconfig-lint/blob/master/tsconfig.json).

**Comment by dsebastien** [comment]
I'm looking at the code now. I think it shouldn't be too complicated to support an external config file

**Comment by dsebastien** [comment]
Do you accept PRs? :)

**Comment by wjohnsto** [comment]
Yeah I'm willing to accept a PR! What are you thinking about in terms of the configuration?

**Comment by dsebastien** [comment]
I want to add a -c and --config arg to tsconfig-lint, which should be the name of the tslint config file to load, assuming that the file should sit in the same folder as tsconfig.json (i.e., under configPath)

**Comment by wjohnsto** [comment]
What if we avoid additional arguments and instead we add a check for `tslint.json` after the checks we do in the `tsconfig.json`. Does that make sense? I'm assuming that most people will have their rules in `tslint.json` since that is what `tslint` uses.

**Comment by dsebastien** [comment]
Indeed, that's also an option, up to you :)

**Comment by dsebastien** [comment]
Code is almost there ^^

**Comment by dsebastien** [comment]
To be more general, i'd do both though

**Comment by dsebastien** [comment]
Default to tslint.json and check if it's there by default and if specified, just override with the provided name

**Comment by wjohnsto** [comment]
My only gripe is that `-c, --config` naming might be confusing since now we have 2 different config files.

**Comment by dsebastien** [comment]
Have you had a chance to look at the PR? :)

**Comment by wjohnsto** [comment]
Should be in v0.8.0
