### ISSUE TITLE
Exit/status code is always 0

### ISSUE THREAD

**Issue by rpatterson** [wjohnsto/tsconfig-lint#6]
I can run tslint on a file that has failures and the exit status is non-zero and the exit status for a file with no failures is 0, both as they should be:

```
rpatterson@rpatterson:~/src/work/newcontext/Soltra/argos/argos-ui$ ./node_modules/.bin/tslint
...
src/app/....ts[63, 56]: missing whitespace
$ echo $?
2
$ ./node_modules/.bin/tslint src/app/...ts
$ echo $?
0
```

But running tsconfig-lint with a config that includes the same files and reports the same failures has an exit status of 0:

```
$ ./node_modules/.bin/tsconfig-lint                                                                                          
Linting 28 files
...
src/app/...ts[63, 56]: missing whitespace

Done with 63 failures.
$ echo $?
0
```

This makes using tsconfig-lint in CI is much more difficult than it need be.

**Comment by wjohnsto** [comment]
This should be the default behavior in v0.10.0

**Comment by rpatterson** [comment]
Doh!  Sorry I forgot to check if I was running the latest.

**Comment by wjohnsto** [comment]
I just published it :), your sanity can be saved!
